// <auto-generated />
using System;
using Early_warning.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Early_warning.Migrations
{
    [DbContext(typeof(FloodContext))]
    [Migration("20250401055231_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Early_warning.FloodCause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Cause")
                        .IsUnique();

                    b.ToTable("FloodCauses");
                });

            modelBuilder.Entity("Early_warning.FloodEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CauseId")
                        .HasColumnType("int");

                    b.Property<int?>("FloodCauseId")
                        .HasColumnType("int");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId1")
                        .HasColumnType("int");

                    b.Property<int>("SeverityId")
                        .HasColumnType("int");

                    b.Property<int?>("SeverityLevelId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CauseId");

                    b.HasIndex("FloodCauseId");

                    b.HasIndex("LocationId");

                    b.HasIndex("LocationId1");

                    b.HasIndex("SeverityId");

                    b.HasIndex("SeverityLevelId");

                    b.ToTable("FloodEvents");
                });

            modelBuilder.Entity("Early_warning.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,6)");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Early_warning.SeverityLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Level")
                        .IsUnique();

                    b.ToTable("SeverityLevels");
                });

            modelBuilder.Entity("Early_warning.FloodEvent", b =>
                {
                    b.HasOne("Early_warning.FloodCause", "Cause")
                        .WithMany()
                        .HasForeignKey("CauseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Early_warning.FloodCause", null)
                        .WithMany("FloodEvents")
                        .HasForeignKey("FloodCauseId");

                    b.HasOne("Early_warning.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Early_warning.Location", null)
                        .WithMany("FloodEvents")
                        .HasForeignKey("LocationId1");

                    b.HasOne("Early_warning.SeverityLevel", "Severity")
                        .WithMany()
                        .HasForeignKey("SeverityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Early_warning.SeverityLevel", null)
                        .WithMany("FloodEvents")
                        .HasForeignKey("SeverityLevelId");

                    b.Navigation("Cause");

                    b.Navigation("Location");

                    b.Navigation("Severity");
                });

            modelBuilder.Entity("Early_warning.FloodCause", b =>
                {
                    b.Navigation("FloodEvents");
                });

            modelBuilder.Entity("Early_warning.Location", b =>
                {
                    b.Navigation("FloodEvents");
                });

            modelBuilder.Entity("Early_warning.SeverityLevel", b =>
                {
                    b.Navigation("FloodEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
